Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "https.test"
  config.vm.network :private_network, type: "dhcp"
  # Ideally we shouldn't be using the vagrant default key
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  # Ansible provisioning for docker and other host config
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "vagrant-host.yml"
    ansible.become = true
  end

  # Copying the container image from host to guest
  config.vm.provision "file", source: "../container/build/petrol-nginx.tar", destination: "/tmp/petrol-nginx.tar"

  # Docker privisioning
  config.vm.provision "shell", path: "shell/docker-setup.sh"
end